config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/product_types', to: 'product_types#index'
  get '/units', to: 'units#index'
  get '/returns', to: 'units#borrowed_list_return'
  get '/checkout', to: 'users#checkout'
  get '/request_checkout', to: 'units#request_checkout'
  get '/request_return', to: 'units#request_return'
  get '/borrowed_units', to: 'units#borrowed_units'
  #get '/edit', to: 'users#edit'
  #admin
  get '/create_user', to: 'users#create_user'
  get '/users', to: 'users#index'
  get '/verify_user', to: 'users#verify_user'
  get '/transactions', to: 'transactions#index'
  resources :users
  resources :transactions
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :product_types, only: [:create, :destroy, :edit, :update]
  resources :units do
    member do
      patch :returnManually
      patch :updateCheckout
      patch :checkout
      patch :returning
      patch :approve
      patch :reject
      patch :approveR
      patch :rejectR
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    #validates :password, presence: true, length: { minimum: 6 }
    
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

   # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    #Need to implement
    # Activates an account.
    # def activate
    #     update_attribute(:activated, true)
    #     update_attribute(:activated_at, Time.zone.now)
    # end
    # # Sends activation email.
    # def send_activation_email
    #     UserMailer.account_activation(self).deliver_now
    # end
    
    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    
    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

    private
        # Converts email to all lower-case.
        def downcase_email
            self.email = email.downcase
        end
        # Creates and assigns the activation token and digest.
        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #Admin restricted pages
  def ensure_admin!
    unless current_user and current_user.admin?
      redirect_to root_url
      flash[:danger] = "You do not have proper authorization"
    end
  end
  def index
    @users = User.paginate(page: params[:page])
    ensure_admin!
  end
  
  def create_user
    ensure_admin!
  end
  def verify_user
    @users = User.paginate(page: params[:page])
    ensure_admin!
  end
  
  #User Pages and also accessible to users
  def ensure_user!
    unless current_user
      redirect_to root_url
      flash[:danger] = "You are not permitted"
    end
  end
  def checkout
    @units = Unit.paginate(page: params[:page])
    ensure_user!
  end
  
  
  #Methods
  def show
    @user = User.find(params[:id])
    if current_user.admin? and current_user == @user
      redirect_to "/units"
    elsif current_user.admin? == false and current_user == @user
      redirect_to "/checkout"
    else
      redirect_to root_url
      flash[:danger] = "You are not permitted"
    end
  end
  def new
    @user = User.new
    if logged_in?
      redirect_to root_url
    end
  end
  def create
    @user = User.new(user_params)
    #Checks if admin is creating 
    if logged_in?
      if @user.save
        @user.update_attribute(:activated, true)
        @user.update_attribute(:activated_at, Time.zone.now)
        #log_in @user
        flash[:success] = "Created a new user"
        redirect_to "/create_user"
      else
        flash[:danger] = "Error Occured when creating a User"
        redirect_back(fallback_location:"/")
      end
    #Else by default for signup
    else
      if @user.save
        #UserMailer.account_activation(@user).deliver_now
        flash[:info] = "Request for activation has been sent, please wait for email to notify that account has been created."
        redirect_to root_url
      else
        render 'new'
      end
    end
  end
  def destroy
    hasItems = false
    Unit.all.each do |unit|
      if unit.location == User.find(params[:id]).name
        if hasItems == false
          hasItems = true
        end
      end
    end
    if hasItems == false
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to '/users'
    else
      flash[:danger] = "User still has items, cannot be deleted"
      redirect_to '/users'
    end
  end
  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes(user_params)
      flash[:success] = "Changed Successfully"
      redirect_back(fallback_location:"/")
    # elsif @user.update_attributes(user_params) and current_user.admin? and current_user
    #   flash[:success] = "Updated Successfully"
    #   redirect_to "/users"
    elsif @user.update(user_params)
      flash[:success] = "Updated Your Profile Successfully"
      redirect_to @user
    else
      #Reloads any current page
      render 'edit'
    end
  end
  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
      flash[:danger] = "You are not permitted"
    end
  end
    
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/users/checkout.html.erb
<!--Checkout Table -->
<h3>Checkout </h3>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">VSU Tag</th>
      <th scope="col">Model</th>
      <th scope="col">Brand</th>
      <th scope="col">Condition</th>
      <!--<th scope="col">Location</th>-->
      <% if current_user.admin? %>
      <th scope="col">Pick User/Checkout</th>
      <% else %>
      <th scope="col">Checkout</th>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <%= will_paginate @units%>
    <% @units.each do |unit| %>
      <% if unit.location == "storage" %>
      <tr>
        
        <td><%= unit.name_id %></td>
        <td><%= unit.vsu_id %></td>
        <td><%= unit.product_type.model %></td>
        <td><%= unit.product_type.brand %></td>
        <td><%= unit.condition %></td>
        <!--<td><%#= link_to 'Edit', "#" %></td>-->
        <% if current_user.admin? %>
        <td>
          <%= form_for unit, url: updateCheckout_unit_path(unit), method: :patch do |f| %>
            <%= f.select :location, User.all.map{|c| [c.name]}, :prompt => "Select One"%>
            <%= f.submit "Checkout", class: "btn btn-primary", id: "admin-checkout" %>
        </td>
        <td>
            
        </td>
          <% end %>
        <%#= select_tag(:location, options_from_collection_for_select(User.all, :id, :name), selected: :location)%>
          <%#= submit_tag("checkout", checkoutA_unit_path }) %>
        <% else %>
          <td>
            <% if unit.requestor == "N/A" %>
              <%= link_to 'Checkout', checkout_unit_path(unit), method: :patch %>
            <% else %>
              Pending for Request
            <%end%>
          </td>
        <%end%>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate @units%>

app/views/users/create_user.html.erb
<% provide(:title, 'Sign up') %>
<h1>Create User</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: User, local: true) do |f| %>
            <%#= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.label :admin, :value => "false" %>
            <br>
            <%= f.label :admin, "No", :value => "false" %>
            <%= f.radio_button :admin, "0" %>
            <%= f.label :admin, "Yes", :value => "true" %>
            <%= f.radio_button :admin, "1" %>
            <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update Your Profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages', form_object: @user %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<!--User Table -->
        <h3>Users </h3>
        <%= will_paginate %>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">User Status</th>
          <th scope="col">Admin Status</th>
          <th scope="col">Delete</th>
          <!--<th scope="col">Edit</th>-->
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <% if user.admin? %>
                <td>Admin</td>
            <% else %>
                <td>Regular User</td>
            <% end %>
            <!--<td><%#= link_to 'Edit', "#" %></td>-->
            <% if user.id == 1 %>
              <td><b>Cannot change status</b></td>
              <td><b>Cannot delete</b></td>
            <% else %>
              <td>
                <%= form_for user do |f| %>
                  <%= f.label :admin, "No", :value => "false" %>
                  <%= f.radio_button :admin, "0", :checked => true %>
                  <%= f.label :admin, "Yes", :value => "true" %>
                  <%= f.radio_button :admin, "1" %>
                  <%= f.submit "Update", class: "btn btn-primary",id: "update-admin-btn" %>
              </td>
              
                  
                <% end %>
              <%#= select_tag(:location, options_from_collection_for_select(User.all, :id, :name), selected: :location)%>
              <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "You sure?" } %></td>
            <% end %>
          </tr>
       
      </tbody>
       <% end %>
       
    </table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="signupBackground">
    <h1>Sign up</h1>
    
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, local: true) do |f| %>
                <%= render 'shared/error_messages', form_object: @user %>
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
                <p><%= link_to "Already a user? Login", login_path %></p>
                <%= f.submit "Sign up", class: "btn btn-primary", id: "sign-up-btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
        <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <h1>
                    <%= gravatar_for @user %>
                    <%= @user.name %>
                </h1>
            </section>
        </aside>
        <div class = "container">
    
        
    
        
      </div>
    </div>
  </div>
</div>

app/views/users/verify_user.html.erb
<!--User Table -->
        <h3>Users </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <!--<th scope="col">User Status</th>-->
          <th scope="col">Accept</th>
          <th scope="col">Reject</th>
          <!--<th scope="col">Location</th>-->
          <!--<th scope="col">Edit</th>-->
        </tr>
      </thead>
      <tbody>
        <%= will_paginate @users%>
        <% User.all.each do |user| %>
          <tr>
            <% if !user.activated %>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "Activate", edit_account_activation_url(user.activation_token,
                email: user.email, id: user.id) %></td>
            <td>
              <%= link_to 'Reject', user, method: :delete, data: { confirm: "You sure?" } %>
            </td>
            <% end %>
            
          </tr>
      </tbody>
       <% end %>
    </table>
    <%= will_paginate @users%>