config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/product_types', to: 'product_types#index'
  get '/units', to: 'units#index'
  get '/returns', to: 'units#borrowed_list_return'
  get '/checkout', to: 'users#checkout'
  get '/request_checkout', to: 'units#request_checkout'
  get '/request_return', to: 'units#request_return'
  get '/borrowed_units', to: 'units#borrowed_units'
  #get '/edit', to: 'users#edit'
  #admin
  get '/create_user', to: 'users#create_user'
  get '/users', to: 'users#index'
  get '/verify_user', to: 'users#verify_user'
  get '/transactions', to: 'transactions#index'
  resources :users
  resources :transactions
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :product_types, only: [:create, :destroy, :edit, :update]
  resources :units do
    member do
      patch :returnManually
      patch :updateCheckout
      patch :checkout
      patch :returning
      patch :approve
      patch :reject
      patch :approveR
      patch :rejectR
    end
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :product_type
  
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
    def ensure_admin!
        unless current_user and current_user.admin?
            redirect_to root_url
            flash[:danger] = "You do not have proper authorization"
        end
    end
    def index
        @units = Unit.paginate(page: params[:page])
        ensure_admin!
    end
    def request_checkout
        @units = Unit.paginate(page: params[:page])
        ensure_admin!
    end
    def request_return
        @units = Unit.paginate(page: params[:page])
        ensure_admin!
    end
    def borrowed_units
        @units = Unit.paginate(page: params[:page])
        ensure_admin!
    end
    
    def ensure_user!
        unless current_user
            redirect_to root_url
            flash[:danger] = "You are not logged in"
        end
    end
    def borrowed_list_return
        @units = Unit.paginate(page: params[:page])
        ensure_user!
    end
    def create
        @unit = Unit.new(units_params)
        if @unit.save
            flash[:success] = "Unit created!"
            # if(@unit.location != "storage")
            #     Transaction.create(category: "Unit Creation w/ user", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
            # end
            redirect_to "/units"
        else
            flash[:danger] = "Error: Unit was not created"
            redirect_to "/units"
        end

    end
    def destroy
        Unit.find(params[:id]).destroy
        flash[:success] = "Unit deleted"
        redirect_to '/units'
        

    end
    def edit
        @unit = Unit.find(params[:id])
        ensure_admin!
        
    end
    #Checkout mainly happens with this function
    def update
        @unit = Unit.find(params[:id])
        #last_location = @unit.location
        if @unit.update_attributes(units_params)
            flash[:success] = "Unit Updated"
            # if(@unit.location != "storage" and @unit.location != last_location)
            #     #As long as location does not equal storage or its last location it will update the transaction history
            #     Transaction.create(category: "Checkout", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
            # end
            #redirect_back(fallback_location:"/")
            redirect_to '/units'

        else
            flash[:danger] = "Error Occured"
        end
        
    end
    #Update function for checkout and transaction record
    def updateCheckout
        @unit = Unit.find(params[:id])
        last_location = @unit.location
        if @unit.update_attributes(units_params)
            flash[:success] = "Unit Checked Out and Transaction Recorded"
            Transaction.create(category: "Checkout", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
            # if(@unit.location != "storage" and @unit.location != last_location)
            #     #As long as location does not equal storage or its last location it will update the transaction history
            #     Transaction.create(category: "Checkout", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
            # end
            redirect_back(fallback_location:"/")
        else
            flash[:danger] = "Error Occured"
        end
    end

    def checkoutA
        Unit.find(params[:id]).update(:location => current_user.name)
        flash[:success] = "User has been selected for checkout"
        redirect_to '/checkout'
        
    end
    def checkout
        Unit.find(params[:id]).update(:requestor => current_user.name)
        flash[:success] = "Unit checkout Request sent to Admins, Please wait for Approval"
        redirect_to '/checkout'
        
    end
    def approve
        @unit = Unit.find(params[:id])
        Transaction.create(category: "Checkout", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
        @unit.update(:location => Unit.find(params[:id]).requestor)
        @unit.update(:requestor => "N/A")
        
        flash[:success] = "Request Approved"
        redirect_to '/request_checkout'
    end
    def reject
        Unit.find(params[:id]).update(:requestor => "N/A")
        Unit.find(params[:id]).update(:location => "storage")
        flash[:success] = "Request Rejected"
        redirect_to '/request_checkout'
    end
    def returning
        Unit.find(params[:id]).update(:returner => current_user.name)
        flash[:success] = "Unit return request sent to Admins, please wait for approval"
        redirect_to '/returns'
        
    end
    def rejectR
        #Unit.find(params[:id]).update(:location => Unit.find(params[:id]).requestor)
        Unit.find(params[:id]).update(:returner => "N/A")
        
        flash[:success] = "Return Request rejected"
        redirect_to '/request_return'
    end
    def approveR
        @unit =  Unit.find(params[:id])
        Transaction.create(category: "Return", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
        @unit.update(:returner => "N/A")
        @unit.update(:location => "storage")
        flash[:success] = "Return Request approved"
        redirect_to '/request_return'
        
    end
    def returnManually
        @unit =  Unit.find(params[:id])
        Transaction.create(category: "Return", unit: @unit.name_id, unit_tag: @unit.vsu_id, user: @unit.location, time: Time.zone.now)
        @unit.update(:returner => "N/A")
        @unit.update(:location => "storage")
        flash[:success] = "Unit manually returned"
        redirect_to '/borrowed_units'
    end
    
    private
        def units_params
            params.require(:unit).permit(:name_id, :vsu_id, :product_type_id, :condition, :location)
        end
end

app/views/units/borrowed_list_return.html.erb
<!--Units Borrowed -->
        <h3>Borrowed Units </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">VSU Tag</th>
          <th scope="col">Model</th>
          <th scope="col">Brand</th>
          <th scope="col">Condition</th>
          <th scope="col">Location</th>
          <!--<th scope="col">Edit</th>-->
          <th scope="col">Return</th>
        </tr>
      </thead>
      <tbody>
      <%= will_paginate @units%>
        <% @units.all.each do |unit| %>
          <% if unit.location != "storage" && unit.location == current_user.name %>
          <tr>
            
            <td><%= unit.name_id %></td>
            <td><%= unit.vsu_id %></td>
            <td><%= unit.product_type.model %></td>
            <td><%= unit.product_type.brand %></td>
            <td><%= unit.condition %></td>
            <td><%= unit.location %></td>
            <!--<td><%#= link_to 'Edit', "#" %></td>-->
            
            <td>
              <% if unit.returner == "N/A" %>
                <%= link_to 'Return', returning_unit_path(unit), method: :patch %>
              <% else %>
              Pending for Verification
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @units%>

app/views/units/borrowed_units.html.erb
<!--Product Units Table -->
        <h3>All Borrowed Units </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">VSU Tag</th>
          <th scope="col">Model</th>
          <th scope="col">Brand</th>
          <th scope="col">Condition</th>
          <th scope="col">Location</th>
          <!--<th scope="col">Edit</th>-->
          <th scope="col">Return Manually</th>
        </tr>
      </thead>
      <tbody>
        <%= will_paginate @units%>
        <% @units.all.each do |unit| %>
          <tr>
            <% if unit.location != "storage" %>
                <td><%= unit.name_id %></td>
                <td><%= unit.vsu_id %></td>
                <td><%= unit.product_type.model %></td>
                <td><%= unit.product_type.brand %></td>
                <td><%= unit.condition %></td>
                <td><%= unit.location %></td>
                <!--<td><%#= link_to 'Edit', "#" %></td>-->
                <td><%= link_to 'Return Manually', returnManually_unit_path(unit), method: :patch %></td>
              </tr>
          <%end%>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @units%>

app/views/units/edit.html.erb
<% provide(:title, 'Edit Unit') %>
<h1>Update Unit</h1>

<br>
    <%= form_with(model: @unit, local: true, id: "form") do |f| %>
        <%= f.label :name_id %>
        <%= f.text_field :name_id, class: 'form-control' %>
        <%= f.label(:vsu_id, 'VSU Tag') %>
        <%= f.text_field :vsu_id, class: 'form-control' %>
        <%= f.label(:product_type, 'Product Type') %>
        <br>
        <%= f.select :product_type_id, ProductType.all.map{|c| [c.model,c.id]}, :prompt => "Select One"  %>
        <br>
        <%= f.label :condition %>
        <%= f.text_field :condition, class: 'form-control' %>
        <%= f.label :location %>
        <br>
        <% list = User.all.map{|c| [c.name]} %>
        <% list.append(['storage'])%>
        <%= f.select :location, list , :prompt => "Select One"%>
        <br>
    <%= f.submit "Save", class: "btn btn-primary", id: "form-btn" %>
    <% end %>

app/views/units/index.html.erb
<!--Product Units Table -->
        <h3>Product Units </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">VSU Tag</th>
          <th scope="col">Model</th>
          <th scope="col">Brand</th>
          <th scope="col">Condition</th>
          <th scope="col">Location</th>
          <!--<th scope="col">Edit</th>-->
          <th scope="col">Edit/Delete</th>
        </tr>
      </thead>
      <tbody>
      <%= will_paginate @units%>
        <% @units.each do |unit| %>
          <tr>
            <td><%= unit.name_id %></td>
            <td><%= unit.vsu_id %></td>
            <td><%= unit.product_type.model %></td>
            <td><%= unit.product_type.brand %></td>
            <td><%= unit.condition %></td>
            <td><%= unit.location %></td>
            <!--<td><%#= link_to 'Edit', "#" %></td>-->
            <td><%= link_to 'Edit',edit_unit_path(unit) %>/<%= link_to 'Delete', unit, method: :delete, data: { confirm: "You sure?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
     <%= will_paginate @units%>
    
      
    <br>
    <%= form_with(model: Unit, local: true, id: "form") do |f| %>
        <%= f.label :name_id %>
        <%= f.text_field :name_id, class: 'form-control' %>
        <%= f.label(:vsu_id, 'VSU Tag') %>
        <%= f.text_field :vsu_id, class: 'form-control' %>
        <%= f.label(:product_type, 'Product Type') %>
        <br>
        <%= f.select :product_type_id, ProductType.all.map{|c| [c.model,c.id]}, :prompt => "Select One"  %>
        <br>
        <%= f.label :condition %>
        <%= f.text_field :condition, class: 'form-control' %>
        <%= f.label :location %>
        <br>
        <% list = User.all.map{|c| [c.name]} %>
        <% list.append(['storage'])%>
        <%= f.select :location, list , :prompt => "Select One"%>
        <br>
    <%= f.submit "Add", class: "btn btn-primary", id: "form-btn" %>
    <% end %>

app/views/units/request_checkout.html.erb
<h3>Request for Checkout </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">VSU Tag</th>
          <th scope="col">Model</th>
          <th scope="col">Brand</th>
          <th scope="col">Condition</th>
          <th scope="col">Location</th>
          <th scope="col">Requestor</th>
          <!--<th scope="col">Edit</th>-->
          <th scope="col">Approve</th>
          <th scope="col">Reject</th>
        </tr>
      </thead>
      <tbody>
        <%= will_paginate @units%>
        <% @units.all.each do |unit| %>
          <% if unit.requestor != "N/A" %>
          <tr>
            
            <td><%= unit.name_id %></td>
            <td><%= unit.vsu_id %></td>
            <td><%= unit.product_type.model %></td>
            <td><%= unit.product_type.brand %></td>
            <td><%= unit.condition %></td>
            <td><%= unit.location %></td>
            <td><%= unit.requestor %></td>
            <!--<td><%#= link_to 'Edit', "#" %></td>-->
            <td><%= link_to 'Approve', approve_unit_path(unit), method: :patch %></td>
            <td><%= link_to 'Reject', reject_unit_path(unit), method: :patch %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @units%>

app/views/units/request_return.html.erb
<h3>Request for Returns </h3>
        <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">VSU Tag</th>
          <th scope="col">Model</th>
          <th scope="col">Brand</th>
          <th scope="col">Condition</th>
          <th scope="col">Location</th>
          <!--<th scope="col">Edit</th>-->
          <th scope="col">Approve</th>
          <th scope="col">Reject</th>
        </tr>
      </thead>
      <tbody>
      <%= will_paginate @units%>
        <% @units.all.each do |unit| %>
          <% if unit.returner != "N/A" %>
          <tr>
            <td><%= unit.name_id %></td>
            <td><%= unit.vsu_id %></td>
            <td><%= unit.product_type.model %></td>
            <td><%= unit.product_type.brand %></td>
            <td><%= unit.condition %></td>
            <td><%= unit.location %></td>
            <!--<td><%#= link_to 'Edit', "#" %></td>-->
            <td><%= link_to 'Approve', approveR_unit_path(unit), method: :patch %></td>
            <td><%= link_to 'Reject', rejectR_unit_path(unit), method: :patch %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @units%>