config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/product_types', to: 'product_types#index'
  get '/units', to: 'units#index'
  get '/returns', to: 'units#borrowed_list_return'
  get '/checkout', to: 'users#checkout'
  get '/request_checkout', to: 'units#request_checkout'
  get '/request_return', to: 'units#request_return'
  get '/borrowed_units', to: 'units#borrowed_units'
  #get '/edit', to: 'users#edit'
  #admin
  get '/create_user', to: 'users#create_user'
  get '/users', to: 'users#index'
  get '/verify_user', to: 'users#verify_user'
  get '/transactions', to: 'transactions#index'
  resources :users
  resources :transactions
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :product_types, only: [:create, :destroy, :edit, :update]
  resources :units do
    member do
      patch :returnManually
      patch :updateCheckout
      patch :checkout
      patch :returning
      patch :approve
      patch :reject
      patch :approveR
      patch :rejectR
    end
  end
end

app/views/layouts/_adminsidebar.html.erb
  <!--sidebar-->
  <nav id = "sidebar">
    <nav class = "navbar navbar-expand-lg navbar-light bg-light" id = "icon-position">
      <div class = "container-fluid">
        <!--main content-->
        <button type= "button" id = "sidebarCollapse" class = "btn btn-info">
          <i class="fas fa-align-left"></i>
          <img id = "nav-icon" alt="pull menu" src = "/assets/nav-icon.png">
        </button>
      </div>
    </nav>
    <!--<div class = "sidebar-header">-->
    <!--  <h3>Bootsrap Slider</h3>-->
    <!--</div>-->
    <ul class = "lisst-unstyled components">
      <!--<p>Provider</p>-->
      <!--<li>-->
      <!--  <a href = "#" style="color: white;"> Dashboard</a>-->
      <!--</li>-->
      <li class = "active">
        <a href = "#homeSubmenu" data-toggle = "collapse" aria-expanded = "false" class = "dropdown-toggle">Inventory</a>
        <ul class = "collapse lisst-unstyled" id="homeSubmenu">
          <li>
            <a href = "/units"> All Inventory</a>
          </li>
          <li>
            <a href = "/product_types"> Add Type</a>
          </li>
          <li>
            <a href = "/borrowed_units"> Borrowed Units</a>
          </li>
          <li>
            <a href = "/checkout"> Checkout</a>
          </li>
          <!--<li>-->
          <!--  <a href = "/returns"> Current List/Return</a>-->
          <!--</li>-->
        </ul>
      </li>
      <li class = "active">
        <a href = "#pageSubmenu" data-toggle = "collapse" aria-expanded = "false" class = "dropdown-toggle">Admin Options</a>
        <ul class = "collapse lisst-unstyled" id="pageSubmenu">
          <li>
            <a href = "/create_user"> Create User</a>
          </li>
          <li>
            <a href = "/verify_user"> Verify User</a>
          </li>
          <li>
            <a href = "/request_checkout"> Requests for Checkout</a>
          </li>
          <li>
            <a href = "/request_return"> Verify Return</a>
          </li>
          <!--<li>-->
          <!--  <a href = "#"> Reports</a>-->
          <!--</li>-->
          <li>
            <a href = "/users"> Users</a>
          </li>
          <li>
            <a href = "/transactions"> Transaction History</a>
          </li>
          <!--<li>-->
          <!--  <a href = "#"> Website Status</a>-->
          <!--</li>-->
        </ul>
      </li>
    </ul>
  </nav>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Last updated: 6/4/2021
    </small>
    <nav>
        <ul>
            <!--<li><#%= link_to "About", '#' %></li>-->
            <!--<li><#%= link_to "Contact", '#' %></li>-->
            <!--li><%#= link_to "Report", '#' %></li>-->
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "CS Inventory Managment", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <% if logged_in? %>
                <li><%= link_to "Users", '/users' %></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                <!--<li><%= link_to "Profile", current_user %></li>-->
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                <%= link_to "Log out", logout_path, method: :delete %>
                </li>
                </ul>
                </li>
                <% else %>
                <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
  <!--sidebar-->
  <nav id = "sidebar">
    <nav class = "navbar navbar-expand-lg navbar-light bg-light" id = "icon-position">
      <div class = "container-fluid">
        <!--main content-->
        <button type= "button" id = "sidebarCollapse" class = "btn btn-info">
          <i class="fas fa-align-left"></i>
          <img id = "nav-icon" alt="pull menu" src = "/assets/nav-icon.png">
        </button>
      </div>
    </nav>
    <!--<div class = "sidebar-header">-->
    <!--  <h3>Bootsrap Slider</h3>-->
    <!--</div>-->
    <ul class = "lisst-unstyled components">
      <!--<p>Provider</p>-->
      <li>
        <!--<a href = "#" style="color: white;"> Dashboard</a>-->
      </li>
      <li class = "active">
        <a href = "#homeSubmenu" data-toggle = "collapse" aria-expanded = "false" class = "dropdown-toggle">Inventory</a>
        <ul class = "collapse lisst-unstyled" id="homeSubmenu">
          <li>
            <a href = "/checkout"> Checkout</a>
          </li>
          <li>
            <a href = "/returns"> Current List/Return</a>
          </li>
        </ul>
      </li>
      <!--<li class = "active">-->
      <!--  <a href = "#pageSubmenu" data-toggle = "collapse" aria-expanded = "false" class = "dropdown-toggle">Options</a>-->
      <!--  <ul class = "collapse lisst-unstyled" id="pageSubmenu">-->
      <!--    <li>-->
      <!--      <a href = "#"> Report Issue</a>-->
      <!--    </li>-->
      <!--  </ul>-->
      <!--</li>-->
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    
    <%= render 'layouts/header' %>
<!--reminder fix code-->    
<div class="wrapper">
  <% if logged_in? %>
    <% if current_user.admin? %>
      <%= render 'layouts/adminsidebar' %>
    <% else %>
      <%= render 'layouts/sidebar' %>
    <%end %>
  <% end %>
  <div id = "content">
    <% if logged_in? %>
    <nav id = "pull-menu">
    <nav class = "navbar navbar-expand-lg navbar-light bg-light" id = "icon-position">
      <div class = "container-fluid">
        <!--main content-->
        <button type= "button" id = "sidebarCollapse" class = "btn btn-info">
          <i class="fas fa-align-left"></i>
          <img id = "nav-icon" alt="pull menu" src = "assets/nav-icon.png">
        </button>
      </div>
    </nav>
    </nav>
    <% end %>
    
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <script>
  $(document).ready(function(){
    $("#sidebarCollapse").on('click', function(){
    $("#sidebar").toggleClass('active');
    $("#pull-menu").css("visibility", "visible");
    });
    $("#pull-menu").on('click', function(){
    $("#sidebar").toggleClass('active');
    $("#pull-menu").css("visibility", "hidden");
    });
  });
</script>
  </body>
</html>